# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release

r_binary_packages:
  - r-cran-mgcv
  - r-cran-mass
  - r-cran-quantreg
  - r-cran-rcpp

notifications:
  email:
    on_failure: change
